/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkAsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/modals.ts
var import_obsidian = require("obsidian");
var NotePickerModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, onChoose, getTitle, showPath) {
    super(app);
    this.onChoose = onChoose;
    this.getTitle = getTitle;
    this.showPath = showPath;
    this.setPlaceholder("Pick a note to link to\u2026");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return `${this.getTitle(file)} ${file.path}`;
  }
  renderSuggestion(match, el) {
    const file = match.item;
    el.createDiv({ text: this.getTitle(file) });
    if (this.showPath) {
      const pathEl = el.createDiv({ text: file.path });
      pathEl.setCssStyles({ color: "var(--text-muted)", fontSize: "var(--font-ui-smaller)" });
    }
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};
var DisplayTextModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
    this.value = "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: "Link text" });
    new import_obsidian.Setting(contentEl).setName("Display text").setDesc("Text to show for the link. Leave empty to use the note's title.").addText((text) => {
      text.setPlaceholder("Display text\u2026");
      text.onChange((value) => this.value = value);
      text.inputEl.addEventListener("keydown", (event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          this.submit();
        }
      });
      window.setTimeout(() => text.inputEl.focus(), 0);
    });
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Continue").setCta().onClick(() => this.submit())
    );
  }
  submit() {
    this.close();
    this.onSubmit(this.value);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  showPathInPicker: true
};
var LinkAsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    // Shown beside the plugin name in the settings sidebar on older Obsidian
    // versions, and next to the plugin's results in 1.13's settings search.
    this.icon = "lucide-link";
    this.plugin = plugin;
  }
  // 1.13.0+: the framework calls this and skips display(), so the setting is
  // indexed for settings search. Pre-1.13.0: this is ignored and display()
  // runs instead (Path B, both kept).
  getSettingDefinitions() {
    return [
      {
        type: "group",
        items: [
          {
            name: "Show file path in picker",
            desc: "Show each note's path as a muted second line under its title in the note picker.",
            control: { type: "toggle", key: "showPathInPicker" }
          }
        ]
      }
    ];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Show file path in picker").setDesc("Show each note's path as a muted second line under its title in the note picker.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showPathInPicker).onChange(async (value) => {
        this.plugin.settings.showPathInPicker = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var POFN_PLUGIN_ID = "property-over-file-name";
var LinkAsPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "link-text-to-note",
      name: "Link text to a note",
      editorCallback: (editor, view) => this.startLinkFlow(editor, view)
    });
    this.addSettingTab(new LinkAsSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  startLinkFlow(editor, view) {
    const selection = editor.getSelection();
    if (selection) {
      this.openNotePicker(editor, view, selection);
      return;
    }
    new DisplayTextModal(
      this.app,
      (displayText) => this.openNotePicker(editor, view, displayText)
    ).open();
  }
  openNotePicker(editor, view, displayText) {
    new NotePickerModal(
      this.app,
      (file) => this.insertLink(editor, view, file, displayText),
      (file) => this.getNoteTitle(file),
      this.settings.showPathInPicker
    ).open();
  }
  insertLink(editor, view, file, displayText) {
    var _a, _b;
    const raw = displayText.trim() || this.getNoteTitle(file);
    const display = this.sanitizeAlias(raw);
    const alias = display && display !== file.basename ? display : void 0;
    const sourcePath = (_b = (_a = view.file) == null ? void 0 : _a.path) != null ? _b : "";
    const link = this.app.fileManager.generateMarkdownLink(file, sourcePath, void 0, alias);
    editor.replaceSelection(link);
  }
  // Collapse whitespace and strip characters that would break a wiki/markdown
  // link alias (handles multi-line selections and selections containing links).
  sanitizeAlias(text) {
    return text.replace(/[[\]|]/g, "").replace(/\s+/g, " ").trim();
  }
  /** A note's Property Over File Name title, or its basename as a fallback. */
  getNoteTitle(file) {
    var _a, _b;
    const propertyKey = this.getPofnPropertyKey();
    if (propertyKey) {
      const value = (_b = (_a = this.app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b[propertyKey];
      if (typeof value === "string") {
        const title = value.trim();
        if (title) return title;
      } else if (typeof value === "number" || typeof value === "boolean") {
        return String(value);
      }
    }
    return file.basename;
  }
  /** The property key configured in Property Over File Name, if installed. */
  getPofnPropertyKey() {
    var _a, _b, _c, _d;
    const pofn = (_b = (_a = this.app.plugins) == null ? void 0 : _a.plugins) == null ? void 0 : _b[POFN_PLUGIN_ID];
    const key = (_d = (_c = pofn == null ? void 0 : pofn.settings) == null ? void 0 : _c.propertyKey) == null ? void 0 : _d.trim();
    return key || null;
  }
};
